# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  # For MongoDB
  config.vm.network "forwarded_port", guest: 27017, host: 27017

  # For ELK
  config.vm.network "forwarded_port", guest: 9292, host: 9292
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 9300, host: 9300

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "ELK" do |ws|
    ws.vm.provider "docker" do |d|
      d.image = "pblittle/docker-logstash"
      d.env = {
        "LOGSTASH_CONFIG_URL" => "https://raw.githubusercontent.com/witlox/cumulonimbi/master/vagrant/logstash.conf"
      }
    end
  end

end
