# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "ELK" do |elk|
    elk.vm.network "forwarded_port", guest: 9292, host: 9292
    elk.vm.network "forwarded_port", guest: 9200, host: 9200
    elk.vm.network "forwarded_port", guest: 9300, host: 9300
    elk.vm.provider "docker" do |d|
      d.image = "pblittle/docker-logstash"
      d.env = {
        "LOGSTASH_CONFIG_URL" => "https://raw.githubusercontent.com/witlox/cumulonimbi/master/vagrant/logstash.conf"
      }
    end
  end

  config.vm.define "MongoDB" do |mdb|
    mdb.vm.network "forwarded_port", guest: 27017, host: 27017
    mdb.vm.provider "docker" do |d|
      d.image = "djbnjack/mongobase"
    end
  end

  config.vm.define "Redis" do |rds|
    rds.vm.network "forwarded_port", guest: 6379, host: 6379
    rds.vm.provider "docker" do |d|
      d.image = "redis"
    end
  end

end
